---
# Player Join Config
# ==================================
# Plugin made by Watermelon
# here you can put whatever message you want to send a player when they join!

join-message: Join Message goes here!
...
